### ISSUE TITLE
windowResized not working for me

### ISSUE THREAD

**Issue by amcc** [Gherciu/react-p5#19]
I'm having trouble getting the windowResized function to work. I've got the following in my code (the console.log is just to try to see if its being called):

`windowResized = p5 => {
    p5.resizeCanvas(p5.windowWidth, p5.windowHeight)
    console.log('resize')
  }`

I've also tried windowResized() { ... }

thanks for any help you can give

**Comment by frommainland** [comment]
Try add windowResized here, it works for me.
```
render() {
        return <Sketch setup={this.setup} draw={this.draw} windowResized={this.windowResized} />;
}
```

**Comment by amcc** [comment]
thanks, will give that a go

**Comment by amcc** [comment]
didn't mean to click the close button - but if it is closed then that's fine too
