### ISSUE TITLE
functional component

### ISSUE THREAD

**Issue by amcc** [Gherciu/react-p5#20]
how would i use this as a functional component rather than a class based one. Not essential, but I'm doing everything else that way and ran into a few errors when i tried to convert it

**Comment by alejandrofloresm** [comment]
I'm using it like this:

```javascript
import React from 'react';
import Sketch from 'react-p5'

const Scene = () => {
 
  const preload = (p5) => {

  }

  const setup = (p5, canvasParentRef) => {
    p5.createCanvas(400, 400).parent(canvasParentRef);
  };

  const draw = p5 => {
    p5.background(35);
  };
  
  return (
    <>
      <Sketch preload={preload} setup={setup} draw={draw} />
    </>
  );
}

export default Scene;
```

**Comment by Gherciu** [comment]
@alejandrofloresm  Thanks for your response....Guys also pls wrap all functions in 'useCallback'.. and all static constants pls declare outside from your ReactFunction to avoid reinitialization on each render do not use 'useMemo' or 'useState' for this purpose)

**Comment by Hahlh** [comment]
Hey @Ghericu ) 

Would you mind explaining why the useCallback is necessary? In the README example it isn't added?
