### ISSUE TITLE
Loading data from local server

### ISSUE THREAD

**Issue by tkdsym2** [Gherciu/react-p5#22]
This is an error about `loadImage()`.

I'm currently running a p5js program in the following environment.

- Environment
  - Node.JS v13.1.0
  - Next.js v9.3.6
  - react v16.13.1

When I try to load the `test.jpg` in `assets` folder, I get the following error.

```
test.jpg:1 GET http://localhost:3000/assets/test.jpg 404 (Not Found)
p5.js says: It looks like there was a problem loading your image. Try checking if the file path [http://localhost:3000/assets/test.jpg] is correct, hosting the image online, or running a local server.[https://github.com/processing/p5.js/wiki/Local-server]
```

How do I get the images on the server to load?

Thank you.

**Comment by Gherciu** [comment]
@tkdsym2  pls access this link http://localhost:3000/assets/test.jpg and say if the image is visible? Seems that the URL to the image is incorrect.

**Comment by OHFloree** [comment]
got the same issue

**Comment by OHFloree** [comment]
> This is an error about `loadImage()`.
> 
> I'm currently running a p5js program in the following environment.
> 
> * Environment
>   
>   * Node.JS v13.1.0
>   * Next.js v9.3.6
>   * react v16.13.1
> 
> When I try to load the `test.jpg` in `assets` folder, I get the following error.
> 
> ```
> test.jpg:1 GET http://localhost:3000/assets/test.jpg 404 (Not Found)
> p5.js says: It looks like there was a problem loading your image. Try checking if the file path [http://localhost:3000/assets/test.jpg] is correct, hosting the image online, or running a local server.[https://github.com/processing/p5.js/wiki/Local-server]
> ```
> 
> How do I get the images on the server to load?
> 
> Thank you.
solved it, you need to import it first:

```javascript
import * as url from 'assets/test.jpg'
let img

function preload(p) {
    img = p.loadImage(url)
}

function setup(p) {
    p.image(img,0,0)
}
```
