### ISSUE TITLE
How do I create Audio?

### ISSUE THREAD

**Issue by cambo2015** [Gherciu/react-p5#27]
I tried to get the AudioIn working, but couldn't figure it out. I'm trying to record audio. How would I call the new AudioIn(). Thanks!

**Comment by archywillhe** [comment]
looks like have to set it up yourself; doesnt appear the p5 audio library is included

**Comment by archywillhe** [comment]
actually is included https://www.npmjs.com/package/p5 so should be quite straightforward. Maybe `p5.AudioIn()`?

**Comment by malutanpetronel** [comment]
the p5.sound.min.js is included

**Comment by thisSource** [comment]
> the p5.sound.min.js is included

Could you please give a code example. I get
TypeError: p5.loadSound is not a function

**Comment by Gherciu** [comment]
Hi p5.sound library is not included in react-p5....you need to include that by yourself 
```
import Sketch from "react-p5";
import "p5/lib/addons/p5.sound";


// and somewhere in your code call......    window.p5.loadSound(...);
```

**Comment by Gherciu** [comment]
Hi @cambo2015  I created a codesandbox with an example "how to use this library with p5.sound"
https://codesandbox.io/s/react-p5-forked-9ixi4?file=/src/index.js
I frequently see this question even if it is super easy to implement please check the example and let me know if it helped...the implementation should be the same even with the next js only difference is as I said with next js you should use "dynamic" to import react-p5 and p5.sound (https://nextjs.org/docs/advanced-features/dynamic-import)

**Comment by Gherciu** [comment]
@malutanpetronel @cambo2015   I've added another example (code snippet) for p5.sound especially for NEXT.js (if you use this as framework)
https://github.com/Gherciu/react-p5/blob/main/README.md#with-p5sound--nextjs-or-other-framework-which-has-support-for-ssr

**Comment by jeremyzilar** [comment]
@Gherciu Thanks for these examples. I am still trying to get [the example you referenced](https://github.com/Gherciu/react-p5/blob/main/README.md#with-p5sound--nextjs-or-other-framework-which-has-support-for-ssr) working with Typescript.
I keep getting `Property 'getAudioContext' does not exist on type`.

**Comment by SixBeeps** [comment]
> @Gherciu Thanks for these examples. I am still trying to get [the example you referenced](https://github.com/Gherciu/react-p5/blob/main/README.md#with-p5sound--nextjs-or-other-framework-which-has-support-for-ssr) working with Typescript. I keep getting `Property 'getAudioContext' does not exist on type`.

I apologize for necroing this thread, but I'm getting this exact same error when trying to get an audio context. Here's the relevant code that's throwing the error:

```js
p5init(p5) {
	if (p5.getAudioContext().state !== 'running') {
		p5.userStartAudio();
	}
	this.audioContext = p5.getAudioContext();
}
```

I have verified that p5 is not undefined or null.
