### ISSUE TITLE
Support p5 version 1.0.0

### ISSUE THREAD

**Issue by akd-io** [Gherciu/react-p5#30]
`p5@1.0.0` was released 5 months ago. I assume react-p5 doesn't need to change to support `p5@1.0.0`, but the peer dependency still says `^0.7.3`, currently installing `p5@0.10.2`.

I assume a change to `>=^0.7.3` might fix it, but I'm no package expert, and wasn't able to test it on my machine.

**Comment by Gherciu** [comment]
@akd-io Hi, yep...sorry I need to update this ... I think tomorrow I will push a commit with this change..and also update on npm)

**Comment by Gherciu** [comment]
@akd-io  version 1.3.5 has been deployed to npm with the updated latest p5 version... in the near future, it will be added as a peer dependency to allow users to install different versions of p5 lib ;)

**Comment by igniscyan** [comment]
@Gherciu Are we still able to declare our own versions of processing?
