### ISSUE TITLE
Canvas stops drawing when invoking useState in next.js

### ISSUE THREAD

**Issue by itshoro** [Gherciu/react-p5#32]
Hey I'm using this Component in a Next.js project to animate a low-poly landscape.
When invoking `useState` (see `_app.js`), the canvas suddenly stops drawing or at least it seems to no longer be visible.

The canvas is still in the DOM, resizing the window seems to fix this. Something similar happens when something is changed in the next.js project and hot-reload is kicking in, so these might be related to one another.

https://codesandbox.io/s/interesting-rgb-r09mf?file=/components/animatedTerrain.js

**Comment by Gherciu** [comment]
@itshoro Hi, pls move all variables like (h, w, rows) outside of React component because of multiple rerenders these vars are redeclared with initial values

**Comment by itshoro** [comment]
This apparently was the problem. Well my very shoddy react knowledge was the culprit. Thanks for your time.
