### ISSUE TITLE
Trouble resolving module in Gatsby

### ISSUE THREAD

**Issue by bomanimc** [Gherciu/react-p5#39]
Hi! I noticed an issue with resolved this module in Gatsby project I'm working on using the latest version (1.3.8).
```
Can't resolve 'react-p5' in '/Users/bomani/Desktop/code/personal/src/pages/experiments'
```
 Switching to 1.3.6 seemed to have resolved the issue. Here's a reference to the code in question if you'd like to take a look and try switching the version of the react-p5 to the latest one and running `npm install` and `gatsby develop`!
https://github.com/bomanimc/personal/tree/noc

**Comment by PiotrKedra** [comment]
I got this error without gatsby using the 1.3.8 version, downgrading to 1.3.6 resolved it

**Comment by touyou** [comment]
I had same problem in Next.js, and also downgrading to 1.3.6 resolved it.

**Comment by Gherciu** [comment]
pls try to reinstall `npm i react-p5@latest` fixed in https://github.com/Gherciu/react-p5/pull/44
