### ISSUE TITLE
No build folder exists after npm install --save react-p5

### ISSUE THREAD

**Issue by PhilAndrew** [Gherciu/react-p5#42]
On my empty nodejs project I ran

`npm install --save react-p5`

There is no build folder, I needed then to checkout this project from git, build it and copy the build folder across to my `node_modules/react-p5/` folder.

**Comment by hug0Hq** [comment]
Duplicate of #43

**Comment by Gherciu** [comment]
pls try to reinstall `npm i react-p5@latest`...it was fixed in https://github.com/Gherciu/react-p5/pull/44
