### ISSUE TITLE
Can't resolve 'react-p5'

### ISSUE THREAD

**Issue by TimoLange98** [Gherciu/react-p5#43]
Hey! I have a problem:
With the following code I get the error 'Module not found: Can't resolve 'react-p5' in 'C:\....'. 
I ran 'npm i p5 react-p5' and also checked the package.json. If I hover over the importet 'Sketch' it even shows the proper information on that. Everything seems to be correct but it just won't work and I couldn't find anything in the Internet.

```
import React, {useState,useRef} from 'react'
import Sketch from 'react-p5'

const Seperator = () => {
   const sketchContainer = useRef(null)
   let currentPage
   const preload = p5 => {
      p5.loadImage('../resources/test.png', img => {
         currentPage = img
      })
   }
   const setup = (p5, sketchContainer) => {
      p5.createCanvas(500, 500, p5.WEBGL).parent(sketchContainer)
   }
   const draw = p5 => {
      p5.image(currentPage, 0, 0)
   }

   return (
      <div ref={sketchContainer}>
         <Sketch preload={preload} setup={setup} draw={draw} />
      </div>
   )
}
export default Seperator
```

**Comment by hug0Hq** [comment]
This error is because the ` ./build/index.js` is not present in the npm package

**Comment by MohammadMitwaly** [comment]
Hello,
I'm also facing a similar issue in a TypeScript project.
After creating a separate component and exporting it:
```typescript
import React from "react";
import Sketch from "react-p5"
import p5Types from "p5"; //Import this for typechecking and intellisense

interface MainSketchProps {
	//Your component props
}

export const MainSketch: React.FC<MainSketchProps> = (props: MainSketchProps) => {
	let x = 50;
	const y = 50;

	//See annotations in JS for more information
	const setup = (p5: p5Types, canvasParentRef : Element) => {
		p5.createCanvas(500, 500).parent(canvasParentRef);
	};

	const draw = (p5: p5Types) => {
		p5.background(0);
		p5.ellipse(x, y, 70, 70);
		x++;
	};

	return <Sketch setup={setup} draw={draw} />;
};
```
Then importing it:
```typescript
import React from 'react';
import './App.css';
import {MainSketch} from './Components/MainSketch';

function App() {
  return (
    <div className="App">
      <MainSketch/>
    </div>
  );
}

export default App;
```
I get this after running `npm start`, I get:
```bash
Module not found: Can't resolve 'react-p5' in 'pathToProject\project-name\src\Components'
```
I created the project using `npx create-react-app --template typescript`

**Comment by hug0Hq** [comment]
@MohammadMitwaly
@Gherciu needs to approve #44 
As a temp fix you can downgrade to v1.3.6

**Comment by AshutoshAgrawal2004** [comment]
@hug0Hq  Thanks for the pull request. Looks like they still haven't approved it though.
Downgrading to lower versions is still showing the same problem. Is there any way to fix it. I am trying to deploy my react app on netlify and keeps failing.

**Comment by TimoLange98** [comment]
@MohammadMitwaly  @AshutoshAgrawal2004  I fixed it by cloning this project, run the build script so it creates a build folder with an index.js in it. That folder you can copy into the react-p5 folder in your node_modules folder of your project.

**Comment by Gherciu** [comment]
pl try to reinstall `npm i react-p5@latest` fixed in https://github.com/Gherciu/react-p5/pull/44
