### ISSUE TITLE
use p5 webcam/VIDEO functionality in react

### ISSUE THREAD

**Issue by nhammad** [Gherciu/react-p5#53]
I am trying to use p5's webcam / video capture functional in my react application. I found an example with Sketch and it worked. However, when I try to change the given sketch to the video thing (code inspired by ml5.js documentation), it does not work because VIDEO is not defined. 
```
let capture;
export const YourComponent: React.FC<ComponentProps> = (props: ComponentProps) => {
	let x = 50;
	const y = 50;

	//See annotations in JS for more information
	// const setup = (p5: p5Types, canvasParentRef: Element) => {
	// 	p5.createCanvas(500, 500).parent(canvasParentRef);
	// };

	// const draw = (p5: p5Types) => {
	// 	p5.background(0);
	// 	p5.ellipse(x, y, 70, 70);
	// 	x++;
	// };

    let capture: p5Types.Element;
    const setup = (p5: p5Types, canvasParentRef: Element) => {
        p5.createCanvas(390, 240);
        capture = p5.createCapture(VIDEO);
        capture.size(320, 240);
        //capture.hide();
      }
      
      const draw = (p5: p5Types) => {
        p5.background(255);
        p5.image(capture, 0, 0, 320, 240);
        p5.filter(INVERT);
      }

      
	return <Sketch setup={setup} draw={draw} />;
};
```

```
Cannot find name 'VIDEO'.
```
It's the same for invert.
Here's something similar but it is in plain javascript, not react. 

https://github.com/ml5js/ml5-library/blob/main/examples/p5js/ImageClassification/ImageClassification_Video/sketch.js
How can I reproduce this in react?

**Comment by Gherciu** [comment]
@nhammad  Hi,
VIDEO is a global variable not part of Scketch p5 instance....
pls try `window.p5.VIDEO`....
every global p5 constant/function should be accessed through `window.p5`

**Comment by nhammad** [comment]
This might not be the best place to ask it but I'm not sure if the problem is with the css or whether I'm failing to understand how the Sketch/videoCapture component really works:

So, I am trying to use p5's VIDEO component in my React application but I am unable to style it. **I want to move it towards a bit right but it's stuck on the extreme left of my screen.** I tried adding padding-left to the css for Sketch but it does not make a difference. But adding paddingTop or paddingBottom does make a difference. If I add a background color to check, the background color is shown at the top so I am not sure where exactly I should be applying the padding css.
```
export const Component: React.FC<ComponentProps> = (props: ComponentProps) => {

    let capture: p5Types.Element;
    const setup = (p5: p5Types, canvasParentRef: Element) => {
        p5.createCanvas(390, 240);
        capture = p5.createCapture(p5.VIDEO);
        capture.size(320, 240);
      }
      
      const draw = (p5: p5Types) => {
      }

      
	return <Sketch setup={setup} draw={draw} className="sketch"/>
	;
};

```
How can I move the video component towards the right?

Codesandbox: https://codesandbox.io/s/objective-wind-yx1gm?file=/src/Video.tsx

**Comment by nhammad** [comment]
Also, why is it showing automatic paddingTop? I mean why isnt it starting from the top and is starting from the middle instead?
