### ISSUE TITLE
Typescript and p5.erase()

### ISSUE THREAD

**Issue by EricWVGG** [Gherciu/react-p5#54]
I bumped into an issue with using erase() and noErase() in Typescript. The interpreter insists that these are unknown properties:
```
const mouseMoved = (p5: p5Types) => {
    p5.erase(255, 0)
    p5.ellipse(p5.mouseX, p5.mouseY, 10)
    p5.noErase()
}
```

They definitely exist, everything works perfectly when I instruct Typescript to ignore these lines.
```
const mouseMoved = (p5: p5Types) => {
    // @ts-ignore
    p5.erase(255, 0)
    p5.ellipse(p5.mouseX, p5.mouseY, 10)
    // @ts-ignore
    p5.noErase()
}
```

**Comment by Gherciu** [comment]
Hi, Types are provided by p5 library not by react-p5..
So I guess that this type is missing in p5 library.
I'll update the p5 library and check maybe in new versions thats resolved.

**Comment by EricWVGG** [comment]
Thank you! 

Otherwise this library is working fantastically. I'll be sure to ping you when the project goes live.
