### ISSUE TITLE
Not able to call createVector

### ISSUE THREAD

**Issue by pathakshashank17** [Gherciu/react-p5#55]
I am trying to call the function `createVector` outside the `setup` and `draw` functions. I have tried `window.p5.createVector`, `createVector` and `p5.createVector`, but all of them cause `is not a function` error. So how should I instead call `createVector` ?

**Comment by Gherciu** [comment]
Hi @pathakshashank17 can you pls provide a reproducible example in codesandbox? Because is strange we had this issue before but by accessing window.p5.createVector should resolve that

**Comment by pathakshashank17** [comment]
Here is the [sandbox](https://codesandbox.io/s/react-p5-forked-1yrvy?file=/src/index.js). My best guess is I am using it in an unintended way.

**Comment by Gherciu** [comment]
Hi @pathakshashank17, yes that's an issue related to how you are using that))
Just try to pass p5 to your `disort` function like in the example below...because here p5 should be the Schetck p5 but not the global one.
```js
const distort = (p5) => {
	p5.createVector(100, 100, 100);
}


draw(p5){
 // other code
 disort(p5)
}
```
