### ISSUE TITLE
react-p5 with p5.sound and tone.js cannot be used at the same time? 

### ISSUE THREAD

**Issue by cordial** [Gherciu/react-p5#56]
If I use the work around to use p5.sound by importing as -

import "p5/lib/addons/p5.sound";

and I am using tone.js in another react class like - 

const osc = new Oscillator("100").toDestination();

I get the following error on page load -
<img width="1004" alt="Screenshot 2021-08-16 at 11 16 07" src="https://user-images.githubusercontent.com/419893/129548501-2936877a-0168-46b6-8e10-99fda9b04bb5.png">

Is this something I shouldn't be doing i.e. you can only use one sound library at a time or is there a way round this? If I remove the p5.sound import the error goes away...

**Comment by Gherciu** [comment]
Hi @cordial  I created a codesandbox with an example "how to use this library with p5.sound"
https://codesandbox.io/s/react-p5-forked-9ixi4?file=/src/index.js
I frequently see this question even if it is super easy to implement please check the example and let me know if it helped...the implementation should be the same even with the next js only difference is as I said with next js you should use "dynamic" to import react-p5 and p5.sound (https://nextjs.org/docs/advanced-features/dynamic-import)

**Comment by Gherciu** [comment]
@cordial   I've added another example (code snippet) for p5.sound especially for NEXT.js (if you use this as framework)
https://github.com/Gherciu/react-p5/blob/main/README.md#with-p5sound--nextjs-or-other-framework-which-has-support-for-ssr
