### ISSUE TITLE
P5 windowResized

### ISSUE THREAD

**Issue by jamesgrubb** [Gherciu/react-p5#63]
Hi, thank you for your work on this package. I wondered if there is a way of implementing p5's `windowResized` function. I'm trying something like the below:
```
export default (props) => {
	colorTeal;
	console.log('🚀 ~ file: index.js ~ line 10 ~ colorTeal', colorTeal);
	const x = props.x;
	const y = props.y;
	const setup = (p5, canvasParentRef) => {
		p5.createCanvas(window.innerWidth, window.innerHeight).parent(
			canvasParentRef
		);
	};

	const draw = (p5) => {
		p5.background('#319795');
		p5.ellipse(x, y, 70, 70);
		x++;
	};
	const windowResized = () => {
		resizeCanvas(window.innerWidth / 2, window.innerHeight / 2);
	};
	// Will only render on client-side
	return <Sketch setup={setup} draw={draw} windowResized={windowResized} />;
};
```

**Comment by thisSource** [comment]
this will work

`
export default (props) => {
	// colorTeal;
	// console.log('🚀 ~ file: index.js ~ line 10 ~ colorTeal', colorTeal);
	// const x = props.x;
	// const y = props.y;
	const setup = (p5, canvasParentRef) => {
		p5.createCanvas(window.innerWidth, window.innerHeight).parent(
			canvasParentRef
		);
	};

	const draw = (p5) => {
    windowResized(p5)
		p5.background('#319795');
		p5.ellipse(100, 100, 70, 70);
		// x++;
	};
	const windowResized = (p5) => {
		p5.resizeCanvas(window.innerWidth / 2, window.innerHeight / 2);
	};
	// Will only render on client-side
	return <Sketch setup={setup} draw={draw}/>;
}`

**Comment by Gherciu** [comment]
@jamesgrubb @thisSource I'm gonna close this issue because I tested and windowResized events works perfectly....
@jamesgrubb try to put there a console log and resize the screen and you'll see that it works.......
The only problem which I see in your code is that you are calling `resizeCanvas` method without `p5.` in front
