### ISSUE TITLE
p5.loadSound in next.js

### ISSUE THREAD

**Issue by thisSource** [Gherciu/react-p5#64]
hello! I would be super happy if anyone could share code where p5 sound library is used with react-p5 and next.js.
keep getting p5.loadSound() is not a function

**Comment by Gherciu** [comment]
Hi can you pls provide a codesandbox with this error...and I'll try to investigate

**Comment by Gherciu** [comment]
@thisSource

**Comment by Gherciu** [comment]
Hi p5.sound library is not included in react-p5....you need to include that by yourself 
```
import Sketch from "react-p5";
import "p5/lib/addons/p5.sound";

// and somewhere in your code call......    window.p5.loadSound(...);
```

Plus don't forget that react-p5 can't be rendered on the Server side because that doesn't make sense....
everything in Next.js which should be rendered only on client should be imported using the "dynamic" util from next.js https://nextjs.org/docs/advanced-features/dynamic-import

**Comment by thisSource** [comment]
Thank you for your response. Highly appreciated. Could you please provide a code example of how you import the library dynamically and play sound? It is a lot to ask for but as a person not too strong in the latest next.js features I am struggling. 
I will contribute to the project.

**Comment by thisSource** [comment]
did anyone get this going in next.js?

**Comment by Gherciu** [comment]
Hi @thisSource I created a codesandbox with an example "how to use this library with p5.sound"
https://codesandbox.io/s/react-p5-forked-9ixi4?file=/src/index.js
I frequently see this question even if it is super easy to implement please check the example and let me know if it helped...the implementation should be the same even with the next js only difference is as I said with next js you should use "dynamic" to import react-p5 and p5.sound  (https://nextjs.org/docs/advanced-features/dynamic-import)

**Comment by Gherciu** [comment]
@thisSource I've added another example (code snippet) for p5.sound especially for NEXT.js
https://github.com/Gherciu/react-p5/blob/main/README.md#with-p5sound--nextjs-or-other-framework-which-has-support-for-ssr
