### ISSUE TITLE
using classes for shapes

### ISSUE THREAD

**Issue by voidsailor** [Gherciu/react-p5#66]
Hi,

I'm having trouble figuring out how to use classes with react-p5.
Consider following example class that should draw a circle and update it's y position:

```
import P5 from "p5"

export class Circle {

    _p5: P5;
    _color: string;
    _diameter: number;
    _position: P5.Vector;

    constructor(p5: P5, color: string, initPosition: P5.Vector, diameter: number) {
        this._p5 = p5;
        this._color = color;
        this._position = initPosition;
        this._diameter = diameter;
    }

    updatePosition = (p5: P5, velocity: number) => {
        this._position.y += velocity;
    }

    display(velocity: number) {
        this._p5.fill(this._color);
        this._p5.circle(this._position.x, this._position.y, this._diameter);
        this.updatePosition(this._p5, velocity);
    }
}
```

According to the original p5.js reference, an object can be initialized in the "setup" function and the "display" method can be invoked from "draw". If I do it like this, the object can be initialized in "setup", but is unknown in "draw".
Initializing the object outside of "setup" and "draw" requires the p5 instance, but I couldn't figure out how to get it from window.p5 (as described here: https://levelup.gitconnected.com/integrating-p5-sketches-into-your-react-app-de44a8c74e91).

Here's also a CodeSandbox example: https://codesandbox.io/s/sharp-andras-g3css?file=/src/App.tsx

**Comment by Gherciu** [comment]
Sorry, this question is not related to react-p5... but to "How to use OOP"
And I'm not gonna teach developers about how to write/declare correct classes and invoke them.
Sorry)
And pls re-read the documentation... 
We use p5.scketches here and you don't actually need the global P5 object.....you have access to your sketch p5 object in any function already (draw, setup,etc)
- Plus your sandbox example is super bad you are invoking Circle class inside a React function which changes at every render....
- Plus the Circle.js file is empty ..loll
You need  to learn how to use OOP and React functional components but not what is bad in your code...sorry this library is for more proficient react devs(

**Comment by voidsailor** [comment]
Thanks for your feedback, I found the obvious reason for my problem (CodeSandbox example is updated as well).

**Comment by Gherciu** [comment]
@voidsailor Yep now the example looks much better....but you still have a problem that will break your code in the future if The App component will be rerendered by his Parent....

The `let circle` variable is declared inside APP which is a Functional component which means that on every render it this function will be executed and by default the "circle" variable will be undefined and you will end up with a situation when in draw function your "circle" variable will be undefined.

To avoid such situations as said in documentation you should move this "circle variable declaration" outside of the App function
or use `useRef()` to avoid redeclare it on every rerender....ex `const circle = useRef()` and the you can assign and read values from it using `circle.current = new Circle()     and use it      circle.current.display()`

**Comment by voidsailor** [comment]
Understood now. I learned something today, thanks @Gherciu ^^
