### ISSUE TITLE
types incompatible between react-p5 and latest @types/p5

### ISSUE THREAD

**Issue by HirokiYoshida837** [Gherciu/react-p5#67]
Hi @Gherciu !

Thank you for keeping maintenance your great this project ;)

When I using this library with latest p5.js (1.4.0) and @types/p5 (1.3.1), I met tsc  errors like below.

```sh
$ npx tsc --noEmit
../src/components/MySketch.tsx:26:22 - error TS2322: Type '(p5: p5Types, canvasParentRef: Element) => void' is not assignable to type '(p5: import("C:/Users/xxxx/Documents/xxxxxx/react-p5/node_modules/@types/p5/index.d.ts"), CanvasParentRef: Element) => void'.
  Types of parameters 'p5' and 'p5' are incompatible.
    Type 'import("C:/Users/hirok/Documents/Code/2022/react-p5/node_modules/@types/p5/index.d.ts")' is missing the following properties from type 'import("C:/Users/xxxx/Documents/xxxxxx/next-p5/node_modules/@types/p5/index.d.ts")': erase, noErase,LABEL, FALLBACK, and 11 more.

26       return <Sketch setup={setUp} draw={draw}/>

```

I think this error has happened by types incompatibility from this commit.
 => [🤖 Merge PR #53358 [p5.js] Added missing type and function declaration… · DefinitelyTyped/DefinitelyTyped@61cd6ff](https://github.com/DefinitelyTyped/DefinitelyTyped/commit/61cd6ffbdec2c6c479851cf22be82d393a955907#diff-a7ec7e2c989867fb54f9cfb1b182212eb3c361e770a99a8dd08fa92ddeab2506)

Can I update these packages  dependencies ? 
- "@types/p5": "0.9.1", => "@types/p5": "1.3.3",
- "p5": "1.1.9" => "p5": "1.3.1"

**Comment by HirokiYoshida837** [comment]
I create this PR. Please check when you can!

[fix: update p5 and @types version in dependencies by HirokiYoshida837 · Pull Request #68 · Gherciu/react-p5](https://github.com/Gherciu/react-p5/pull/68)

**Comment by Gherciu** [comment]
@HirokiYoshida837  thanks, I merged this PR and published it.
