### ISSUE TITLE
"window not defined" error in NextJS

### ISSUE THREAD

**Issue by rohan-kiratsata** [Gherciu/react-p5#70]
Facing "ReferenceError: window is not defined" error while using react-p5 in the NextJS app.

**Comment by 0p3r4t0r** [comment]
@rohan-kiratsata 
Did you ever find a fix for this?

**Comment by rohan-kiratsata** [comment]
oh yeah, I was dumb... it is already mentioned in the docs https://github.com/Gherciu/react-p5#using-it-in-an-ssr-environement

**Comment by Gherciu** [comment]
@0p3r4t0r ^

**Comment by 0p3r4t0r** [comment]
I came across the same error while working with [Gatsby](https://www.gatsbyjs.com/).

For anyone encountering the same issue see [Gatsby docs: Using Client-Side Only Packages](https://www.gatsbyjs.com/docs/using-client-side-only-packages/#workaround-4-load-client-side-dependent-components-with-loadable-components)

Solved by wrapping the component in `Loadable`
```
const LoadablePage = Loadable(
  () => import("path-to-page-with-p5-sketch")
);

export default LoadablePage;
```

**Comment by Gherciu** [comment]
@0p3r4t0r Yep, please open a PR and I'll be more than happy to merge it.....thanks
