### ISSUE TITLE
Typing not available for the p5 declared in the window.

### ISSUE THREAD

**Issue by MD-REHMAN** [Gherciu/react-p5#80]
I found that typing was missing on the window / global object. 
This can be fixed in 2 ways:
1. **Quick Fix**:  
By making the declaration in your repo like the one below.
```
import type p5 from "p5";

declare global {
	interface Window {
		p5: typeof p5;
	}
}
```

2. **Ideal Solution**: 
Add it to this package itself. Because the assignment of p5 is being done in the package only.
I will be creating a PR for this shortly.

**Comment by Gherciu** [comment]
Thanks @MD-REHMAN
