### ISSUE TITLE
issues with p5 sound library import

### ISSUE THREAD

**Issue by miguellacorte** [Gherciu/react-p5#83]
Hey, I'm using react (created with Vite config boilerplate) and I'm trying to add p5 sound to a react component using the NPM package called react-p5. However, just adding the import statement `"p5/lib/addons/p5.sound";` generates this error: 

> Uncaught DOMException: Failed to execute 'registerProcessor' on 'AudioWorkletGlobalScope': An AudioWorkletProcessor with name:"recorder-processor" is already registered.
    at blob:http://127.0.0.1:5173/232e2cdb-311b-4020-bffc-c365ef399dc2:279:1
127.0.0.1/:1 Uncaught DOMException: Failed to execute 'registerProcessor' on 'AudioWorkletGlobalScope': An AudioWorkletProcessor with name:"sound-file-processor" is already registered.
    at blob:http://127.0.0.1:5173/95ed1720-c20d-4f97-a434-e19e58b44025:189:1
127.0.0.1/:1 Uncaught DOMException: Failed to execute 'registerProcessor' on 'AudioWorkletGlobalScope': An AudioWorkletProcessor with name:"amplitude-processor" is already registered.
    at blob:http://127.0.0.1:5173/5c00e408-269e-41c4-9331-9534d4908080:252:1

here is the full repo:
https://github.com/miguellacorte/Collaborative_drum_seqeuncer

any ideas what might be going on?

_Originally posted by @miguellacorte in https://github.com/Gherciu/react-p5/issues/10#issuecomment-1280562404_

**Comment by Gherciu** [comment]
Please re read our README.md there is a section about how to use and import sound library in different react frameworks....Thanks!

**Comment by miguellacorte** [comment]
Hell please excuse me, I attached the wrong repo in the original comment. I just updated it 

for future reference, here is the correct repo where I was getting the error, (commit #3 from 17th oct, 2022.) 
https://github.com/miguellacorte/drum_sequencer_p5.js_react

I changed app structure from Vite to Create React App and now everything is working fine , however i still get the same errors...

**Comment by Gherciu** [comment]
@miguellacorte 
In the repo you shared.. I see you are using p5 but not react-p5 .... so the question is not related to react-p5 since you are not using it at all..?
Make sure that you send the correct link to your demo repository where I actually will be able to see tat you are using react-p5
