### ISSUE TITLE
Multiple instances of react-p5 don't seem to work

### ISSUE THREAD

**Issue by martijnvanderpol** [Gherciu/react-p5#86]
Hey all,

I made a p5 sketch using react-p5 and I want to add multiple instances of that sketch on the same page. Unfortunately, it doesn't work as expected. It displays two canvases in the DOM (defaultCanvas0 and defaultCanvas1) but only the last canvas works. The first one doesn't render anything.

The progress passed is used to change the RGB values ​​of the background while scrolling.

```
import { Box } from '@chakra-ui/react';
import dynamic from 'next/dynamic';
import p5Types from 'p5';

const Sketch = dynamic(() => import('react-p5'), { ssr: false });

interface BackgroundAnimationProps {
  progress: number;
}

const BackgroundAnimation = ({ progress }: BackgroundAnimationProps) => {
  let resizeCheck: NodeJS.Timeout;

  const setup = (p5: p5Types, canvasParentRef: Element) => {
    p5.createCanvas(p5.windowWidth, p5.windowHeight).parent(canvasParentRef);
    window.p5 = p5;
  };

  const draw = () => {
    const red = window.p5.map(progress, 0, 100, 0, 255);
    const green = window.p5.map(progress, 0, 100, 255, 0);
    const blue = window.p5.map(progress, 0, 100, 0, 255);

    window.p5.background(red, green, blue);
  };

  const resizeWindow = () => {
    window.p5.resizeCanvas(window.p5.windowWidth, window.p5.windowHeight);
  };

  const windowResized = () => {
    clearTimeout(resizeCheck);
    resizeCheck = setTimeout(resizeWindow, 100);
  };

  return (
    <Box position="absolute" top={0} left={0} zIndex={-1} width="100%" height="100%">
      <Sketch setup={setup} draw={draw} windowResized={windowResized} />
    </Box>
  );
};

export default BackgroundAnimation;
```

Any help would be greatly appreciated. Thanks in advance!

**Comment by Gherciu** [comment]
Hi @martijnvanderpol 
In the code you shared I see a bunch of weird antipatterns like:
```
window.p5 = p5;
```
Why do you rewrite the global p5 with the sketch one..  these are 2 different things .. you already should have a global p5 object from `p5 library` itself which BTW is different from the sketch one.
Every method has as the first argument its own p5 Instance which you should use (As I said these should be different instances for each sketch you should not use the global one in this example at least)

**Comment by martijnvanderpol** [comment]
That's it @Gherciu. I feel stupid, because that actually makes a lot of sense, haha. Don't know what I was thinking; I was probably looking for a quick fix to not pass the p5 to every function. Anyway; thanks for your clear explanation.
