### ISSUE TITLE
windowWidth not defined

### ISSUE THREAD

**Issue by gaurav-2-0-0-2** [Gherciu/react-p5#90]
So I was doing this 
canvas = p5.createCanvas(windowWidth, windowHeight);  
To put the canvas as a background but it's showing this error
Uncaught ReferenceError: windowWidth is not defined
Is there any solution to this ?

**Comment by Gherciu** [comment]
Hi @gaurav-2-0-0-2  ,
Try that `window.p5.windowWidth`

**Comment by ShivamOfTheSingh** [comment]
I used p5.windowWidth, which worked for me too
