### ISSUE TITLE
Can we update package.json to have the latest and greatest p5.js version?

### ISSUE THREAD

**Issue by rdsilver** [Gherciu/react-p5#96]
Latest is [v1.7.0](https://github.com/processing/p5.js/tree/v1.7.0), this repo is now a couple of years behind.

New package.json would look like, updating types as well.

```
  "dependencies": {
    "@types/p5": "1.6.2",
    "opencollective-postinstall": "2.0.2",
    "p5": "1.7.0"
  },
  ```

**Comment by Gherciu** [comment]
Yep, please open a PR for that and I'll merge and publish it
