### ISSUE TITLE
Passing additional arguments to functions draw() and setup()

### ISSUE THREAD

**Issue by happy-cutman** [Gherciu/react-p5#98]
Hi

It would be cool to be able to store these functions in separate files if they get very large. Perhaps there is an example of how to achieve something like this:

![Screenshot_5](https://github.com/Gherciu/react-p5/assets/43891296/15bcd486-a176-4c9f-8a84-9585fcb0498a)

And thanks for this great library)

**Comment by Gherciu** [comment]
Not sure what's the problem) you can move draw function in a separate file and then import
